---
# tasks file for setup-apache-role
#
- name: installing httpd
  yum:
     name: httpd
     state: installed
  when: ansible_os_family == "RedHat"


- name: installing apache2
  apt:
     name:  apache2
     state: present
  when: ansible_os_family == "Debian"
- name: copy index.html
  copy:
     src: /home/ansadmin1/index.html
     dest: /var/www/html
     mode: 0666

